# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-01 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardDetail',
            fields=[
                ('cardId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('title', models.CharField(default=b'', max_length=100)),
                ('type', models.SmallIntegerField(default=0)),
                ('source', models.CharField(default=b'', max_length=30)),
                ('reply', models.CharField(default=b'', max_length=30)),
                ('hotCount', models.IntegerField(default=0)),
                ('replyDate', models.DateTimeField()),
                ('isSearchPassWord', models.CharField(default=b'', max_length=40)),
                ('tag', models.CharField(default=b'', max_length=40)),
                ('createTime', models.DateTimeField()),
                ('content', models.TextField(default=b'')),
                ('replyContent', models.TextField(default=b'')),
            ],
            options={
                'db_table': 'll_card_detail',
            },
        ),
    ]
