# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-02 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ll_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carddetail',
            options={'verbose_name': '\u5408\u80a5\u76f4\u901a\u8f66', 'verbose_name_plural': '\u5408\u80a5\u76f4\u901a\u8f66'},
        ),
        migrations.AlterField(
            model_name='carddetail',
            name='type',
            field=models.SmallIntegerField(choices=[(0, '\u65e0'), (1, '\u54a8\u8be2'), (2, '\u5efa\u8bae')], default=0),
        ),
    ]
