# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-09 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ll_admin', '0002_auto_20180602_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('cardId', models.CharField(auto_created=True, max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(default=b'', max_length=30)),
                ('age', models.IntegerField(default=0)),
                ('phone', models.IntegerField(default=0)),
                ('wechat', models.CharField(default=b'', max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('bankNum', models.IntegerField(default=20)),
                ('bank', models.CharField(default=b'', max_length=30)),
                ('card', models.CharField(default=b'', max_length=30)),
                ('address', models.CharField(default=b'', max_length=100)),
                ('wife', models.CharField(default=b'', max_length=20)),
                ('wifePhone', models.IntegerField(default=0)),
                ('father', models.CharField(default=b'', max_length=20)),
                ('fatherPhone', models.IntegerField(default=0)),
                ('mother', models.CharField(default=b'', max_length=20)),
                ('motherPhone', models.IntegerField(default=0)),
                ('workmate', models.CharField(default=b'', max_length=20)),
                ('workmatePhone', models.IntegerField(default=0)),
                ('friend', models.CharField(default=b'', max_length=20)),
                ('friendPhone', models.IntegerField(default=0)),
                ('workUnit', models.CharField(default=b'', max_length=40)),
                ('work', models.CharField(default=b'', max_length=20)),
                ('unitPhone', models.IntegerField(default=0)),
                ('workAddress', models.CharField(default=b'', max_length=100)),
                ('socialSecurity', models.CharField(default=b'', max_length=30)),
            ],
            options={
                'db_table': 'register_user',
                'verbose_name': '\u91d1\u878d\u6ce8\u518c\u7528\u6237',
                'verbose_name_plural': '\u91d1\u878d\u6ce8\u518c\u7528\u6237',
            },
        ),
    ]
