# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-09 08:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ll_admin', '0003_registeruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 12, 9, 8, 10, 27, 876446, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeruser',
            name='updateTime',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2018, 12, 9, 8, 10, 40, 180180, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
